#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-common
Version  : 3.3.1
Release  : 1
URL      : https://github.com/confluentinc/common/archive/v3.3.1.tar.gz
Source0  : https://github.com/confluentinc/common/archive/v3.3.1.tar.gz
Source1  : http://packages.confluent.io/maven/io/confluent/common-parent/3.3.1/common-parent-3.3.1.pom
Source2  : http://packages.confluent.io/maven/io/confluent/common-utils/3.3.1/common-utils-3.3.1.jar
Source3  : http://packages.confluent.io/maven/io/confluent/common-utils/3.3.1/common-utils-3.3.1.pom
Source4  : http://packages.confluent.io/maven/io/confluent/common/3.3.1/common-3.3.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: mvn-common-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
Confluent Commons
=================
Contains 3 libraries: [metrics](metrics), [config](config), [utils](utils).

%package license
Summary: license components for the mvn-common package.
Group: Default

%description license
license components for the mvn-common package.


%prep
%setup -q -n common-3.3.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-common
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-common/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-common/NOTICE
cp licenses/LICENSE.apache2.txt %{buildroot}/usr/share/package-licenses/mvn-common/licenses_LICENSE.apache2.txt
cp licenses/LICENSE.bsd.txt %{buildroot}/usr/share/package-licenses/mvn-common/licenses_LICENSE.bsd.txt
cp licenses/LICENSE.mit.txt %{buildroot}/usr/share/package-licenses/mvn-common/licenses_LICENSE.mit.txt

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-common/LICENSE
/usr/share/package-licenses/mvn-common/NOTICE
/usr/share/package-licenses/mvn-common/licenses_LICENSE.apache2.txt
/usr/share/package-licenses/mvn-common/licenses_LICENSE.bsd.txt
/usr/share/package-licenses/mvn-common/licenses_LICENSE.mit.txt
